### ISSUE TITLE
silent build errors: maybe dep.py should detect if input is a valid fortran file

### ISSUE THREAD

**Issue by nbren12** [BoxLib-Codes/BoxLib#15]
I was trying to compile the GettingStarted_C tutorial code and I got an error message:

```
#!/bin/sh
#Building f90/F90 dependency File ...
../../Tools/F_scripts/dep.py --prefix o/2d.gnu.EXE \
            --temp_dir f/2d.gnu.EXE \
            --cpp "cpp -E -traditional-cpp -P" \
            --defines "-DBL_LANG_FORT -DNDEBUG -DBL_GCC_VERSION='6.2.0' -DBL_GCC_MAJOR_VERSION=6 -DBL_GCC_MINOR_VERSION=2 -DBL_SPACEDIM=2 -DBL_FORT_USE_UNDERSCORE -DBL_Darwin -I. -I../../Src/C_BaseLib" \
            --f90_preprocess "cat  " work_on_data_2d.f90 ../../Src/C_BaseLib/BaseFab_nd.f90 ../../Src/C_BaseLib/threadbox.f90 ../../Src/C_BaseLib/MultiFabUtil_2d.f90 ../../Src/C_BaseLib/mempool_f.f90 ../../Src/C_BaseLib/bl_fort_module.F90 > d/2d.gnu.EXE/f90.depends
warning: module bl_fort_module required by ../../Src/C_BaseLib/BaseFab_nd.f90 not found
#Traceback (most recent call last):
#  File "../../Tools/F_scripts/dep.py", line 333, in <module>
#    doit(prefix_pass, args.search_path.split(), args.files, cpp_pass, debug=args.debug)
#  File "../../Tools/F_scripts/dep.py", line 276, in doit
#    if provides_obj != sf.obj():
#UnboundLocalError: local variable 'provides_obj' referenced before assignment
```

After debugging `dep.py` using pdb, I found that the reason the error occurred is because the file referenced by `SourceFile.cpp_name` was not a proper fortran file. 

```
$ cat f/2d.gnu.EXE/F90PP-bl_fort_module.F90
dyld: Library not loaded: /usr/local/lib/libmpc.3.dylib
  Referenced from: /usr/local/libexec/gcc/x86_64-apple-darwin15.0.0/5.3.0/cc1
  Reason: image not found
cpp: internal compiler error: Trace/BPT trap: 5 (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
```

This build error is something I will probably have to fix on my side, but it would have been nice if the build process had alerted me to this. Perhaps `dep.py` could be modified to detect if the file at `cpp_name` is indeed a valid fortran file.

**Comment by zingale** [comment]
can you provide an example that demonstrates this?  What were you trying to compile?

**Comment by drummerdoc** [comment]
Also, curious about the warning:

warning: module bl_fort_module required by ../../Src/C_BaseLib/BaseFab_nd.f90 not found

**Comment by zingale** [comment]
actually, looking at the output, it looks like the problem was that `cpp` crashed.  So one fix would be to check the return code from `cpp` and abort with an error if there is a problem with `cpp`.

But the question is -- why does your `cpp` crash?

What machine, OS, compiler, etc. are you trying this on?

**Comment by zingale** [comment]
looking at the line that was sent to `dep.py`, there are a lot of files missing on that line, so that explains the missing module.  Not sure what is setup wrong there.

I have:
```
Building f90/F90 dependency File ...
../../Tools/F_scripts/dep.py --prefix o/2d.gnu.EXE \
            --temp_dir f/2d.gnu.EXE \
            --cpp "cpp -E -traditional-cpp -P" \
            --defines "-DBL_LANG_FORT -DNDEBUG -DBL_GCC_VERSION='6.2.1' -DBL_GCC_MAJOR_VERSION=6 -DBL_GCC_MINOR_VERSION=2 -DBL_SPACEDIM=2 -DBL_FORT_USE_UNDERSCORE -DBL_Linux -I. -I../../Src/C_BaseLib" \
            --f90_preprocess "cat  " work_on_data_2d.f90 ../../Src/C_BaseLib/BaseFab_nd.f90 ../../Src/C_BaseLib/threadbox.f90 ../../Src/C_BaseLib/MultiFabUtil_2d.f90 ../../Src/C_BaseLib/mempool_f.f90 ../../Src/C_BaseLib/bl_fort_module.F90 > d/2d.gnu.EXE/f90.depends 
```

**Comment by zingale** [comment]
final thought -- is it possible that you have the `cpp` aliased to `g++` or the C compiler instead of the preprocessor?

**Comment by nbren12** [comment]
Thanks for replying so fast. I think my compilers were all messed up...as usual, but I fixed them now.  
That said I really had to do some digging with the python debugger to figure out what my problem was. I opened this issue because the build process didn't tell me what my problem was by reporting an error. 

On my system, the `cpp` preprocessor was broken, but the `g++` compiler worked. Therefore 99% of the build process worked, but the only step which failed was the preprocessing of the ".F90" source files using `cpp`. The first place the error was caught was in `dep.py`, and that message didn't even indicate that the problem file was `cat f/2d.gnu.EXE/F90PP-bl_fort_module.F90`.

**Comment by nbren12** [comment]
Basically, I think `dep.py` should be altered to report errors in its preprocessing steps.

**Comment by zingale** [comment]
okay, that's what I thought.  So the question is, if `cpp` is not really the preprocessor, how should we have the script detect this? `dep.py` inherits the name of the preprocessor from the BoxLib build variable `FORT_CPP`

**Comment by nbren12** [comment]
Maybe `dep.py` could return an error if the `cpp` process returns something other than 0.

**Comment by nbren12** [comment]
Maybe something like this could be added at Line 109 of dep.py
```
        stdout, rc = run(command, outfile=processed_file)

        if rc == 0:
            sf.cpp_name = processed_file
        else:
            raise ValueError("cpp process failed for {}".format(self.name))
```

**Comment by nbren12** [comment]
actually this won't work because the command which is run by dep.py is
```
"cpp <bunch of stuff> | cat  "
```
So `cat` return 0, even if `cpp` fails.

**Comment by nbren12** [comment]
BTW, the "cat" comes from the `---f90_preprocess "cat  "` flag to `dep.py`

**Comment by zingale** [comment]
I can change that

The cat is only there cause the F90 BoxLib did that originally and I preserved its behavior when I wrote `dep.py`.  This is because that build system had a postprocessing build variable, but I don't think it is actually used for any systems.  

But I can split these up in python, instead of using a pipe.

Can't do this tonight, but probably over the weekend.

**Comment by zingale** [comment]
alternately we can get the return code from the first part of the pipe through the BASH `PIPESTATUS` variable:

http://stackoverflow.com/questions/13919956/error-checking-pipe-commands-made-in-python-for-unix

**Comment by nbren12** [comment]
I am not familiar with the PIPESTATUS variable. I just made a pull request which replaces "cat " with `if [[ $? ]] ;then; cat ; else; exit -1; fi`. It seems to work for me. I tested it on the GettingStarted_C example, and put a fake `cpp` executable in my path. For example,

```
$ cat /usr/local/bin/cpp
#!/bin/sh

echo "not a CPPP function"
exit -1
```

**Comment by WeiqunZhang** [comment]
But we cannot assume bash is being used.
