### ISSUE TITLE
Confusing error message when a F90 file in F90EXE_sources does not exist.

### ISSUE THREAD

**Issue by WeiqunZhang** [BoxLib-Codes/BoxLib#19]
Suppose in `Make.package` there is,

  `F90EXE_sources += superstring.F90`

Since superstrings cannot be found, `dep.py` silently dies.  The error message of make is something like

  `Unable to open MODULE file bl_fort_module.mod`

This message is confusing and misleading.  If `dep.py` just ignores unfound files and moves on to next file, the make system will then print out a more meaningful message like a .f90 file in f90EXE_sources is missing.

  ` make: *** No rule to make target o/3d.pgi.DEBUG.EXE/superstring.o`

**Comment by WeiqunZhang** [comment]
Assign this to Mike.

**Comment by zingale** [comment]
I'll fix this only if the name `superstring` means that you are working on a BoxLib 10-dimensional string theory fluids code...

**Comment by zingale** [comment]
actually, I don't think the issue is that dep.py silently dies.

Since the `F90EXE_sources` are part of the dependencies for making `f90.depends`:

```
$(depEXETempDir)/f90.depends: $(f90EXE_sources) $(F90EXE_sources)                                                                                                                                   
        @if [ ! -d $(depEXETempDir) ]; then mkdir -p $(depEXETempDir); fi                                                                                                                           
        @if [ ! -d $(f77EXETempDir) ]; then mkdir -p $(f77EXETempDir); fi                                                                                                                           
        @echo "Building f90/F90 dependency File ..."                                                                                                                                                
        $(MODDEP) $(DEP_CHECK_OPTS) --prefix $(objEXETempDir) \                                                                                                                                     
            --temp_dir $(f77EXETempDir) \                                                                                                                                                           
            --cpp "$(FORT_CPP)" \                                                                                                                                                                   
            --defines "-DBL_LANG_FORT $(CPPFLAGS) $(fincludes)" \                                                                                                                                   
            --f90_preprocess "$(F90PREP)" $^ > $(depEXETempDir)/f90.depends 
```
`dep.py` is never called in this situation.  `make` thinks that it first needs to first create `superstring.F90`, so it can satisfy the dependencies that are needed by that rule.  But 
it doesn't know how to make the file `superstring.F90`, so the dependencies are never met, and `dep.py` is not called.

So this problem exists further up the chain.

**Comment by zingale** [comment]
We _could_ remove the dependencies from the `f90.depends` target.  I need to think about whether that is safe.  I _think_ it should be...

**Comment by WeiqunZhang** [comment]
But we need $(f90EXE_sources) $(F90EXE_sources) to be prerequisites of
f90.depends so that make can automatically use vpath to search those files
so that $^ passed into `dep.f90` has the paths, not just file names.


Weiqun

**Comment by zingale** [comment]
Yes, you're right, that's the reason.  So I don't think we can handle this with dep.py

**Comment by WeiqunZhang** [comment]
A way to fix this is remove `-` from `-include .../f90.depends`.  This
makes f90.depends a target that cannot be ignored.  Then the error message
points to missing *superstring*.  The only downside is at the beginning of
make we will see a warning,

Make.rules:159: d/3d.gnu.DEBUG.EXE/f90.depends: No such file or directory

Weiqun

**Comment by zingale** [comment]
I'll leave that to you to decide

**Comment by WeiqunZhang** [comment]
I am going to remove the `-`.
