### ISSUE TITLE
Invalid reference to `LMC-tests.ini` in the regression test README

### ISSUE THREAD

**Issue by RemiLehe** [BoxLib-Codes/BoxLib#7]
The regression test config file `LMC-tests.ini` was recently removed from the BoxLib repository. However, the `README` in `Tools/RegressionTesting/` still mentions it as an example. 

Should it be changed to `VARDEN-tests.ini` instead (for instance), with corresponding changes in the text of the README?

**Comment by zingale** [comment]
I've added an `example-tests.ini` that explains all of the parameters.  Not sure the best way to fix up the `README`, but perhaps it should just suggest looking at the `example-tests.ini` file now?

@drummerdoc added the documentation to the `README` originally, perhaps he has thoughts.

**Comment by drummerdoc** [comment]
I just modified the README to refer to the new example added by @zingale
