### ISSUE TITLE
Regression tests: pass some of the parameters via command line

### ISSUE THREAD

**Issue by RemiLehe** [BoxLib-Codes/BoxLib#8]
When specifying regression tests (which are to be run on the test server), the parameters of the run are given through an input file. 

However, in normal runs, it is also possible to specify some parameters via command line options. This may be useful for the regression tests, because sometimes we want to test one given physical situation with several, smallish variations (e.g. varying the order of accuracy of a solver, varying the direction of the flow of a gas/plasma). In this case, it would be cumbersome to create one input file per test (esp. this could be hard to maintain/modify in the long term), and it would be much better to pass the one parameter that varies, through the command line.

Could this be possible with the regression test interface (i.e. the `.ini` files) ?

**Comment by zingale** [comment]
try the version on `development`.  I just added a test parameter called `runtime_params` -- this should do what you want.

**Comment by RemiLehe** [comment]
Thanks a lot! That works perfectly well.
And thanks for solving the issue that fast!
